ALTER TABLE trove_classifiers ADD COLUMN l2 INTEGER;
ALTER TABLE trove_classifiers ADD COLUMN l3 INTEGER;
ALTER TABLE trove_classifiers ADD COLUMN l4 INTEGER;
ALTER TABLE trove_classifiers ADD COLUMN l5 INTEGER;
